services:
  postgres:
    image: postgres:16
    container_name: employee-postgres
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: employee-backend
    restart: always

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      OLLAMA_HOST: ${OLLAMA_HOST}
  frontend:
    build: ./frontend
    container_name: employee-frontend
    restart: always

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:
  postgres_data: